apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray
  template:
    metadata:
      labels:
        app: ray
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: ray
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/FitApp-html.zip"
        - name: Vless_UUID
          value: "0f2cbf84-1354-4156-af87-095ce4b0dd91"
        - name: Vless_Path
          value: "/0f2cbf84-1354-4156-af87-095ce4b0dd91-vless"
        - name: Vmess_UUID
          value: "0f2cbf84-1354-4156-af87-095ce4b0dd91"
        - name: Vmess_Path
          value: "/0f2cbf84-1354-4156-af87-095ce4b0dd91-vmess"
        - name: Share_Path
          value: "/v2link"
